version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=012093
  redis:
    image: "redis:latest"
  nginx:
    restart: always # as need to awlays be running
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server # look inside this director from the root folder
    volumes:
      - /app/node_modules # everything relevant inside /app which is shown in Dockerfile.dev in which WORKDIR /app. Dont overwrite this
      - ./server:/app # look at server directory and copy everything in the app folder
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres # all the information is in docker documention inside docker hub--> postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client: # added client as not to always rebuild from ground up when run same as top
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
